# Generated by Django 2.2 on 2019-04-21 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20190420_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed_by',
            field=models.ManyToManyField(related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
